"""Add statuses

Revision ID: 230909587e6f
Revises: dc3b0885acdd
Create Date: 2021-10-02 18:41:18.201075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230909587e6f'
down_revision = 'dc3b0885acdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('questions', sa.Column('status_id', sa.Integer()))
    op.create_foreign_key(None, 'questions', 'statuses', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'status_id')
    op.drop_table('statuses')
    # ### end Alembic commands ###
